version: '3'
services:
  php-fpm:
    image: php-pdfjsviewer
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-php
    user: "${DUID:-0}:${DGID:-0}"
    volumes:
      - ./:/var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=pdfjsviewer-docker
